[package]
name = "GravitacaoUniversal"
version = "0.1.0"
edition = "2021"
authors = ["Anderson Rezende <andersonrezende17@hotmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lldb = "0.0.11"
speedy2d = "2.1.0"